# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: nest-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "secret123"]
    volumes:
      - redis-data:/data   # ✅ Named volume, mounted to /data in container
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis-data: # ✅ Define the named volume