export const CONSTANT = {
  CREDS_TAKEN: 'Credentials taken',
  USERNAME_TAKEN: 'Ouch! Username is Taken',
  onUserRegister: 'user.register',
  RESET_MAIL: (mail) => `A reset email has been sent to ${mail}.`,
  CONFIRM_MAIL_SENT: (mail: string) =>
    `A confirmation email has been successfully sent to ${mail}. Please check your inbox and click the provided link to complete the process.`,
  sendConfirmationMail: 'confirmation.mail.request',
  onEmailConfirmationSend: 'user.confirmation.mail.send',
  onEmailConfirmation: 'user.confirmed.mail',
  onPasswordChange: 'user.password.change.success',
  USER_NOT_FOUND: 'User not found',
  AuthQ: 'auth-queue',
  BusinessQ: 'business-queue',
  onUserLogin: 'user.login',
  onPasswordReset: 'user.password.reset.success',
  INCORRECT_CREDS: 'Incorrect Credentials',
  MAIL_UNVERIFIED: 'Email has not been verified',
  OOPS: `Ooops! Something went wrong, this is not you!`,
  OOPs: 'Oops! Something went wrong!',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  REFRESH_TOKEN_EXPIRED: 'Refresh token expired',
  REFRESH_TOKEN_NOTFOUND: 'Refresh token not found',
  REFRESH_TOKEN_NOTFORUSER: 'Refresh token does not belong to the user',
  BUSINESS_PROFILE_EXISTS: 'Business profile already exists for this user',
  BUSINESS_PROFILE_NOTFOUND: 'Business profile not found',
  BUSINESS_PROFILE_REQUIRED: 'You must have a business profile to create client or invoice',
  BUSINESS_PROFILE_REQUIRED_FOR_VIEWING: 'You must have a business profile to view clients',
  BUSINESS_PROFILE_CREATED: 'Business profile created successfully',
  BUSINESS_PROFILE_UPDATED: 'Business profile updated successfully',
  onBusinessProfileCreated: 'business.profile.created',
  CLIENT_UPDATE_FORBIDDEN: 'You are not allowed to update this client',
  CLIENT_NOT_FOUND: 'Client not found',
  CLIENT_DELETE_FORBIDDEN: 'You are not allowed to delete this client',
  UNAUTHORIZED: 'Unauthorized',
  PASSWORD_NOT_MATCH: 'Password Do Not Match',
  PASSWORD_CHANGED: 'Password has been changed',
  CLIENT_CREATE_FORBIDDEN: 'You are not allowed to create an invoice for this client.',
  INVOICE_NOT_FOUND: 'Invoice not found or access denied.',
  INVOICE_UPDATE_FORBIDDEN: 'You are not allowed to update this invoice.',
  INVOICE_DELETE_FORBIDDEN: 'You are not allowed to delete this invoice.',
  INVOICE_DELETE_SUCCESS: 'Invoice deleted successfully.',
};

export const MAIL = {
  noreply: 'mondayitohowo3@gmail.com',
  waitListSubject: 'Welcome to Envoice App',
  waitListFrom: 'The Envoice Team',
  urlLogin: "Envoice Login: Here's the secure login link you requested",
  passwordReset: 'Envoice: Password  Reset',
  confirmEmail: 'Envoice: Email Verification',
  welcomeMail: 'Envoice: Welcome Onboard',
  passswordChange: 'Envoice Security: Your Password has been changed successfully',
};
